### ISSUE TITLE
Explorer's Compass Translation Pack Missing "Ancient City" & "Trail Ruins". Have Fixed That For You.

### ISSUE THREAD

**Issue by rrrexfield** [HuanGeiWoLiuGeBi/Minecraft-Mod-Chinese#1]
Added "Ancient City" & "Trail Ruins":
[zh_cn.json](https://github.com/HuanGeiWoLiuGeBi/Minecraft-Mod-Chinese/files/14373655/zh_cn.json)

**Comment by HuanGeiWoLiuGeBi** [comment]
Already upload to the repositry as "ExplorersCompass-1.20.4-1.3.4-forge.jar.json", thanks
已经上传，文件名为“ExplorersCompass-1.20.4-1.3.4-forge.jar.json”，谢谢
